move to Kotlin Gradle build file
comsysto/spring-core-bootcamp-starter pull request #1
Opened 2019-06-07 11:47 UTC by Endron

Syntax and autocompletion in IntelliJ is much better when useing the newer Kotlin
DSL. So it should be easier when we have to hack something on the fly in
the training.

2019-07-09 17:18 UTC, Silencer- requested changes
Comments have to be discussed.

2019-07-09 17:18 UTC, Silencer- commented on build.gradle.kts
> +     * Spring Data JPA to access data using JPA
These dependencies are added during the training. So, I would suggest to add these to the documentation except we want to ease the dependency stuff. Maybe a mob decides to use JDBC instead of Hibernate :D.

2019-07-09 17:18 UTC, Silencer- commented on build.gradle.kts
> +    implementation("org.glassfish.jaxb:jaxb-runtime:2.3.2")
Have to be removed because it causes errors on startup. Tomcat starts but errors are logged. Furthermore this dependency is not needed and it is included in the Hibernate transient dependencies. It has to be excluded there as well. Maybe we have to update our documentation

2019-07-09 17:18 UTC, Silencer- commented on build.gradle.kts
> +    implementation("org.hibernate:hibernate-core:5.4.1.Final")
We have to exclude the jaxb runtime because it causes errors on Tomcat startup (see next comment). Maybe we have to update our documentation.

```
implementation("org.hibernate:hibernate-core:5.4.1.Final") {
        exclude("org.glassfish.jaxb", "jaxb-runtime")
}
```

2019-07-10 11:54 UTC, Endron commented on build.gradle.kts
> +     * Spring Data JPA to access data using JPA
Last time you complained that it was so much trouble to get Hibernate working in combination with all the other stuff. So I added a test to ensure it does work.
And if they decide to use plain JDBC, they can allways just use the Datasource directly without going through JPA.

2019-07-10 13:27 UTC, Endron commented on build.gradle.kts
> +    implementation("org.hibernate:hibernate-core:5.4.1.Final")
done

2019-07-10 19:42 UTC, Silencer- commented on build.gradle.kts
> +     * Spring Data JPA to access data using JPA
I would prefer to have a good documentation with all needed stuff in there. But yes, you are right. Every time we complain about Hibernate stuff :D. The good thing is we have already to projects with this setup ;).

2019-07-11 18:41 UTC, Silencer- reviewed
Comments discussed and resolved

2019-07-11 18:41 UTC, Silencer- approved these changes

2019-07-11 18:42 UTC, merged